name: PR ìë™ ë¼ë²¨ë§ ë° ë‹´ë‹¹ì í• ë‹¹

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-labels-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add labels and assign PR creator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_CREATOR=${{ github.event.pull_request.user.login }}

          # Add labels
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
          -d '{"labels":["ë§¤ìš´ë§›ğŸ”¥", "ì§„í–‰ ì¤‘ ğŸƒ"]}'

          # Assign PR creator
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/assignees \
          -d "{\"assignees\":[\"$PR_CREATOR\"]}"
